checks:
    php: true
build:
    nodes:
        analysis:
            environment:
                php: 7.0.20
            tests:
                override:
                    - command: phpcs-run
                      use_website_config: true
                    - php-scrutinizer-run

filter:
    excluded_paths:
        - 'Test/*'
tools:
    external_code_coverage:
        timeout: 2400
    php_sim: true
    php_cpd: false
    php_code_coverage:
        enabled: false
    php_cs_fixer:
        config:
            level: psr2
        filter:
            excluded_paths:
                - 'Test/*'
    php_mess_detector:
        config:
            rulesets:
                - codesize
                - unusedcode
                - naming
                - design
            naming_rules:
                short_variable:
                    minimum: 2
        filter:
            excluded_paths:
                - 'Test/*'
