sudo: required

services:
  - docker

language: php

before_script:
  - composer install

script:
  - docker run -e CODE_CLIMATE_TOKEN=$CODE_CLIMATE_TOKEN -v /home/travis/build/webstream-framework/Container:/workspace/ webstream/module-container /bin/sh -c 'vendor/bin/phpunit --configuration phpunit.xml | vendor/bin/test-reporter'

php:
  - 7.0

env:
  global:
    secure: "a2V9PORKKJ4f254rzqmLaTRLB+B/82jJpMC9cjybbZGxlP83Jrzs/mTcyiPjr1J7OQVRROQQG1FEe1KaVVgHugLKxoxerK5jNKz2fn/uXg2wfBSGkiDwScH1YHvZpKp3ELBU/fILKHJhebvHMBJ5ZpexVBfnszcT3AYDjAunh0DAPnNJf6vgd6pkv0Y4k5g1eoTou/6mvI7KaadyBFaQKLvja7LYeOOcJvk3nOj2a4t3yJQjG9M1jyuipOAfwW4XO6YdZi0q35u1GzdhdbiBSzNp4RwEBGQUr1rFKTzVJmV5e/+zEJ2O0qlNxJ+7deGxlZoDFjdHEXwY8NjgpwUcBqH4uoM16TKIYDgdh3h1nlyVEbPMMZzFJdJ1wVBFPPTZZCMUL5HXgT591MFp0uC0PkBTXBBqkCswJUL4YIp9cNsf1m2tVsjLBi4W1xQ/dG1GWasOIh8wQWqialDeNgQnpMhYMqSXf0GK3xYSBNCRNSit/oDgqapcMHGtyrG7GGac+XZJUGSkIRJGOSu3WONyBQsOtseEnYUDCkXBYhWOS4GCuvuX/roSc+JUDt8M1En6lCN+PdtQ75M2s+ASDUjNmFQWS+u03bU3pGPU7OmqmFXqZV5I16oVuhsD2KG+xKJkLv8QZJNsz6KG2dHU+3CdgGPSz3ivYh4K4TNd+phh16w="

notifications:
  slack:
    secure: tobcQWs5nYA4dk9FkGsYEc7NKTOfwwB43eu4mAa6Iqmr5rRF8fpj0iebwfTrkXBcOCbqfwbr4OMWQ2Dq5PuAp0NlCkHGBr6QH4COzjopO/qOSllVkxnlwi/SKYLcrLdtWdwUCJRbpp72UWCJgq/mhP1ksJf6TtlzpCc5fkO0gxJNUvMb/uUqKUWebHK4bNtNTWE5ffy7Mnxh33Ad+CTV0bqPRuRgwkh0kR4lv/83ew+EzXkxzFPppy4BJMtuBqSDx2RFsY5d8ejwVTJzVz1JLMAKzvrf5VXU+EndeaIx68zDT0bwwyq2H07ovVrL4CTkbI2a4yJDZHPhLee9JQ1fVIS7idV30ChY8drsI1xQDKYkE/vaXjlKE/cB6uOE245X+Ht6uhILTJpwjHSu0CHX3RdyWSXnSg0AsaPZN2g/58W9CzfAK9w6tgVPtxhAE81L+7De9BehEfyUfDN5EN1o4C1KWH9LLw8z6Ha19DG2d/xhJOWSMFu64TiwkuQ3lb14x/R/bcO8rJpxcpnTp10r6NIRAMJKnbMiOmmzgu7EONiUPkjIFuf57p7/rCjGLCqE8OYOhh/xt1sWzn0T17ztzKTlhoJtBq6pvkbRY8OdGsfjUvlvbEJG9zi2qqv2d8DLhGXtFWu39+A1YfEwrdi/BANuLx7vLYHYRczjveyWAlw=
